# main text of home
name: Utsav Shukla
bio: Need a little time to wake up

# twitter summary info
description: Here I'll write articles on Coding, Technology, History and Manchester (ofcourse!)

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://github.com/us241098/us241098.github.io/blob/master/Utsav_Resume.pdf

url: https://us241098.github.io/
# your url: http://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-141384270-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname:  # enter this from your disqus account

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: utsav_US7
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
spotify: 6c0nf5wj8ib5k60edly8utiv4?si=yFVLsVRdRJy_7z0apLtsQA
github: us241098
gitlab: us241098
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
reddit: yautslil
#medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: ushukla_be17@thapar.edu

authors:
    johndoe:
        name: Utsav Shukla
        bio: Technology, Pop Culture and Social Media
        external-image: false
        picture: assets/images/profile.jpg
        twitter: utsav_US7


# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: false

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: ["travis.sh", "Rakefile", "README.md", "Gemfile", "Gemfile.lock", "FAQ.md"]
